FROM online-registry.cn-hongkong.cr.aliyuncs.com/okbase/golang:1.24.4-just-foundry AS builder

WORKDIR /root

COPY ./op-ufm /root

RUN CGO_ENABLED=0 make ufm

FROM online-registry.cn-hongkong.cr.aliyuncs.com/okbase/alpine:3.18.3-okg1

RUN apk add --no-cache jq curl bash ca-certificates bind-tools

COPY --from=builder /root/bin/ufm /usr/local/bin/ufm
COPY --from=builder /root/entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

WORKDIR /app

EXPOSE 8080
EXPOSE 7002

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
CMD ["ufm", "/app/config.toml"]